POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3333/videos

###


PUT http://localhost:3333/videos/2dc95e7a-843f-41f6-92ef-830e7727472a
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/2dc95e7a-843f-41f6-92ef-830e7727472a